name: Market Briefing Bot

on:
  schedule:
    - cron: '15 19 * * *'  # TOK
    - cron: '15 2 * * *'   # LON
    - cron: '45 8 * * *'   # NY
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py
